import { Movie } from '../domain/movie'

export const movies: Movie[] = [
  {
    slug: 'the-shining',
    title: 'The Shining',
    year: '1980',
    released: '13 Jun 1980',
    runtime: '146 min',
    genre: 'Drama, Horror',
    director: 'Stanley Kubrick',
    writer: 'Stephen King, Stanley Kubrick, Diane Johnson',
    actors: 'Jack Nicholson, Shelley Duvall, Danny Lloyd',
    plot: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
    awards: '6 wins & 9 nominations',
    poster: 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    imdbRating: '8.4',
    imdbVotes: '1,103,358',
    type: 'movie',
    boxOffice: '$45,634,352',
  },
  {
    slug: 'sinister',
    title: 'Sinister',
    year: '2012',
    released: '12 Oct 2012',
    runtime: '110 min',
    genre: 'Horror, Mystery, Thriller',
    director: 'Scott Derrickson',
    writer: 'Scott Derrickson, C. Robert Cargill',
    actors: 'Ethan Hawke, Juliet Rylance, James Ransone',
    plot: 'A controversial true-crime writer finds a box of Super 8 home movies in his new home, revealing that the murder case he is currently researching could be the work of an unknown serial killer whose legacy dates back to the 1960s.',
    awards: '3 wins & 14 nominations',
    poster: 'https://m.media-amazon.com/images/M/MV5BMjI5MTg1Njg0Ml5BMl5BanBnXkFtZTcwNzg2Mjc4Nw@@._V1_SX300.jpg',
    imdbRating: '6.8',
    imdbVotes: '278,524',
    type: 'movie',
    boxOffice: '$48,086,903',
  },
  {
    slug: 'a-nightmare-on-elm-street',
    title: 'A Nightmare on Elm Street',
    year: '1984',
    released: '16 Nov 1984',
    runtime: '91 min',
    genre: 'Horror',
    director: 'Wes Craven',
    writer: 'Wes Craven',
    actors: 'Heather Langenkamp, Johnny Depp, Robert Englund',
    plot: 'Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in rea...',
    awards: '6 wins & 7 nominations',
    poster: 'https://m.media-amazon.com/images/M/MV5BNzFjZmM1ODgtMDBkMS00NWFlLTg2YmUtZjc3ZTgxMjE1OTI2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    imdbRating: '7.4',
    imdbVotes: '262,329',
    type: 'movie',
    boxOffice: '$25,624,448',
  },
]
